### ISSUE TITLE
Question: forcefully redraw entire screen?

### ISSUE THREAD

**Issue by NikitaIvanovV** [termbox/termbox2#18]
Hello there!

In my program the UI gets messed up because another program needs to write to the stdout. How can I forcefully reload the screen to prevent it? `tb_clear()` and `tb_present()` don't redraw entire screen, only the cells that were changed by termbox itself. I found out that shutting down and initializing termbox does the thing but I feel like there's a better solution.

**Comment by git-bruh** [comment]
You could probably fill all the termbox cells with `' '` (Looping for `tb_height()` and `tb_width()`) after exiting the program to allow termbox to clear them. This is quite hacky aswell and I'd personally prefer the `tb_shutdown()` and `tb_init()` method.

Could you describe what the program does? I'm pretty sure the output will be messed up if termbox is still initialized. For instance, this is what happens when i just call tb_init(), exit the program and try to print some stuff in the terminal:

```
λ printf "Test\nNewline\nAnother\n"
                                   Test
                                       Newline
                                              Another
                                                     λ 
                                                       λ
```

**Comment by NikitaIvanovV** [comment]
You're right, it's better to shutdown termbox completely in this case. Thanks!
