### ISSUE TITLE
Do bold/underline/reverse/italic work in all output modes besides TB_OUTPUT_TRUECOLOR?

### ISSUE THREAD

**Issue by mitchellwrosen** [termbox/termbox2#22]
The code seems to indicate the answer is "yes":

https://github.com/termbox/termbox2/blob/4ac33796ccb5276436fc269ade9ffbe36e205c51/termbox.h#L2806-L2826

But the docs only mention all four modifiers under `TB_OUTPUT_NORMAL`:

```
/* Sets the termbox output mode. Termbox has three output modes:
 * 1. TB_OUTPUT_NORMAL     => [1..8]
 *    This mode provides 8 different colors:
 *      TB_BLACK, TB_RED, TB_GREEN, TB_YELLOW,
 *      TB_BLUE, TB_MAGENTA, TB_CYAN, TB_WHITE
 *    Colors may be bitwise OR'd with attributes:
 *      TB_BOLD, TB_UNDERLINE, TB_REVERSE, TB_ITALIC
 *
 *    Example usage:
 *      tb_set_cell(x, y, '@', TB_BLACK | TB_BOLD, TB_RED);
 *
 * 2. TB_OUTPUT_256        => [0..255]
 *    In this mode you get 256 distinct colors:
 *      0x00 - 0x07: the 8 colors as in TB_OUTPUT_NORMAL
 *      0x08 - 0x0f: TB_<color> | TB_BOLD
 *      0x10 - 0xe7: 216 different colors
 *      0xe8 - 0xff: 24 different shades of grey
 *
 *    Example usage:
 *      tb_set_cell(x, y, '@', 184, 240);
 *      tb_set_cell(x, y, '@', 0xb8, 0xf0);
 *
 * 3. TB_OUTPUT_216        => [0..216]
 *    This mode supports the 3rd range of TB_OUTPUT_256 only, but you don't need
 *    to provide an offset.
 *
 * 4. TB_OUTPUT_GRAYSCALE  => [0..23]
 *    This mode supports the 4th range of TB_OUTPUT_256 only, but you dont need
 *    to provide an offset.
 *
 * 5. TB_OUTPUT_TRUECOLOR  => [0x000000..0xffffff]
 *    This mode provides 24-bit color on supported terminals. The format is
 *    0xRRGGBB.
 *
 * If mode is TB_OUTPUT_CURRENT, the function returns the current output mode.
 *
 * The default output mode is TB_OUTPUT_NORMAL.
 */
```

Furthermore (if they are valid in other modes), it's unclear to me why in TB_OUTPUT_256, the ranges `0x08` - `0x0f` would just be equivalent to bold versions of the 8 basic colors. It seems like you can then get, for example, bold red in two ways:

- 0x0102
- 0x0008

So that's confusing :)

Thanks for the help!

**Comment by adsr** [comment]
Hey, thanks for pointing this out. I agree it is confusing.

Bold, underline, etc are separate escape codes from colors, so any terminal with those caps should be able to apply them in any color mode. The only reason we don't support bold etc in `TB_OUTPUT_TRUECOLOR` is because the `TB_BOLD` flags would collide with 24-bit colors. We could address this by introducing `TB_TRUECOLOR_BOLD` which would occupy the upper 8 bits of a 32-bit int so as to not intefere with 24-bit colors. (See https://github.com/termbox/termbox2/issues/16.)

As for how this actually appears to end users, the results may differ depending on terminal emulator. On my setup (xfce4-terminal, xterm-256color compatible), the range `0x08 - 0x0f` in `TB_OUTPUT_256` produces "bright" colors, not bold. You can pair both dull and bright red with bold:

![red colors](https://i.imgur.com/tVWY26B.png)

xfce4-terminal also has an option to "Show bold text in bright colors" which I have enabled, so I guess that doesn't apply to 256-color mode. I'm curious how other terminal emulators handle it.

If you'd like, feel free to submit a PR to change the comment about `0x08 - 0x0f` to something less misleading like:

```
0x08 - 0x0f: bright versions of the above
```

**Comment by mitchellwrosen** [comment]
Great, thanks for the explanation! Sure, I'll submit that PR - it'll just be what you've written above, though; it sounds fine to me.
