### ISSUE TITLE
TB_BOLD as background attribute

### ISSUE THREAD

**Issue by nekrogenesis** [termbox/termbox2#24]
Using `TB_BOLD` as the background attribute in `tb_print*` causes the printed text to blink in the 
same frequency as the terminal cursor. (I don't know how known or intentional this is.)

To reproduce it:
```c
#define TB_IMPL
#include <termbox.h>
struct tb_event ev;
int main() {
	tb_init();
	tb_hide_cursor();	// (doesnt resolve the issue)
	while (1) {
		tb_peek_event(&ev, 33);
		if (ev.ch == 'q')
			break;
		tb_print(0, 0, 0, 0 | TB_BOLD, "test");
		tb_present();
	}
	tb_shutdown();
	return 0;
}
```

**Comment by adsr** [comment]
Hello, thanks for filing an issue. This is intentional behavior carried over from legacy termbox. The implementation is bit arbitrary in that it lets `TB_REVERSE` apply to either fg or bg, but `TB_UNDERLINE` applies to fg only and is ignored as a bg attribute. I documented this in 7abe663. 16-bit attributes can accommodate 4 more `TB_*` flags, so there's no reason we couldn't make a `TB_BLINK` flag if desired, and maybe let all style flags apply to fg or bg equally.

**Comment by adsr** [comment]
Added `TB_BLINK` in 195aae907d0d7138fec789377f9d1889e1661e0a.
